import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import cn from 'classnames';
import {Footer, Header, Sidebar } from '../components';
import classNames from 'classnames';
import styles from './layout.module.css';

const inter = Noto_Sans({
  subsets: ["cyrillic"],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Hospital',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <div className={styles.body}>
            {children}
          </div>
          <Footer className={styles.footer}/>
      </div>
    </body>
  </html>
  )
}
