import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'

const inter = Noto_Sans({
  subsets: ["cyrillic"],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Hospital',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
